name: mood_match
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  lottie: ^2.6.0
  flutter_sequence_animation: ^4.0.0
  flutter_native_splash: ^1.2.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.3
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  dio: ^5.3.3
  url_launcher: ^6.1.14
  unicons: ^2.1.1
  go_router: ^11.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#1B1B1B"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/animations/splash.json
    - assets/animations/splash2.json
